### ISSUE TITLE
dApp Demo Work & Prototyping

### ISSUE THREAD

**Issue by Shadowfiend** [tallycash/tally-extension#417]
The goal here is to get a working prototype of dApp connections that is good enough for partners to play with integrating their dApps with Tally. End-to-end functionality isn't needed, but this is exploratory to inform the development of the real, security-context-respecting solution.

This work will likely be finished without a merged PR, as the prototype is exploratory rather than being meant for inclusion.

**Comment by greg-nagy** [comment]
https://github.com/tallycash/tally-dapp-integration-samples
- [x] web3-react simple demo
- [x] web3-react official demo
- [x] onboard.js official demo

Maybe later:
- [ ] webmodal demo
